# This file has been generated by node2nix 1.9.0. Do not edit!

{ pkgs ? import <nixpkgs> { inherit system; }, system ? builtins.currentSystem
, nodejs ? pkgs."nodejs-16_x" }:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib python2 runCommand writeTextFile writeShellScript;
    inherit pkgs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
    nodejs = pkgs.nodejs-16_x;
  };
in import ./node-packages.nix {
  inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
  inherit nodeEnv;
}
