declare const currencyCodeMap: {
    readonly AE: "AED";
    readonly AT: "EUR";
    readonly BE: "EUR";
    readonly BG: "BGN";
    readonly BR: "BRL";
    readonly CA: "CAD";
    readonly CH: "CHF";
    readonly CN: "CNY";
    readonly CZ: "CZK";
    readonly DE: "EUR";
    readonly DK: "DKK";
    readonly ES: "EUR";
    readonly FI: "EUR";
    readonly FR: "EUR";
    readonly GB: "GBP";
    readonly GR: "EUR";
    readonly HK: "HKD";
    readonly HR: "HRK";
    readonly HU: "HUF";
    readonly ID: "IDR";
    readonly IE: "EUR";
    readonly IL: "ILS";
    readonly IN: "INR";
    readonly IQ: "IQD";
    readonly IT: "EUR";
    readonly JP: "JPY";
    readonly KR: "KRW";
    readonly KW: "KWD";
    readonly LI: "CHF";
    readonly LU: "EUR";
    readonly MA: "MAD";
    readonly MC: "EUR";
    readonly ME: "EUR";
    readonly MX: "MXN";
    readonly NL: "EUR";
    readonly NO: "NOK";
    readonly NZ: "NZD";
    readonly PL: "PLN";
    readonly PT: "EUR";
    readonly RO: "RON";
    readonly RS: "RSD";
    readonly RU: "RUB";
    readonly SA: "SAR";
    readonly SE: "SEK";
    readonly SG: "SGD";
    readonly SI: "EUR";
    readonly TH: "THB";
    readonly TR: "TRY";
    readonly TW: "TWD";
    readonly UA: "UAH";
    readonly US: "USD";
    readonly ZA: "ZAR";
};
declare const languageMap: {
    readonly aa: readonly ["Afar", "Afar"];
    readonly ab: readonly ["Abkhazian", "Аҧсуа"];
    readonly af: readonly ["Afrikaans", "Afrikaans"];
    readonly ak: readonly ["Akan", "Akana"];
    readonly am: readonly ["Amharic", "አማርኛ"];
    readonly an: readonly ["Aragonese", "Aragonés"];
    readonly ar: readonly ["Arabic", "العربية"];
    readonly as: readonly ["Assamese", "অসমীয়া"];
    readonly av: readonly ["Avar", "Авар"];
    readonly ay: readonly ["Aymara", "Aymar"];
    readonly az: readonly ["Azerbaijani", "Azərbaycanca / آذربايجان"];
    readonly ba: readonly ["Bashkir", "Башҡорт"];
    readonly be: readonly ["Belarusian", "Беларуская"];
    readonly bg: readonly ["Bulgarian", "Български"];
    readonly bh: readonly ["Bihari", "भोजपुरी"];
    readonly bi: readonly ["Bislama", "Bislama"];
    readonly bm: readonly ["Bambara", "Bamanankan"];
    readonly bn: readonly ["Bengali", "বাংলা"];
    readonly bo: readonly ["Tibetan", "བོད་ཡིག / Bod skad"];
    readonly br: readonly ["Breton", "Brezhoneg"];
    readonly bs: readonly ["Bosnian", "Bosanski"];
    readonly ca: readonly ["Catalan", "Català"];
    readonly ce: readonly ["Chechen", "Нохчийн"];
    readonly ch: readonly ["Chamorro", "Chamoru"];
    readonly co: readonly ["Corsican", "Corsu"];
    readonly cr: readonly ["Cree", "Nehiyaw"];
    readonly cs: readonly ["Czech", "Česky"];
    readonly cu: readonly ["Old Church Slavonic / Old Bulgarian", "словѣньскъ / slověnĭskŭ"];
    readonly cv: readonly ["Chuvash", "Чăваш"];
    readonly cy: readonly ["Welsh", "Cymraeg"];
    readonly da: readonly ["Danish", "Dansk"];
    readonly de: readonly ["German", "Deutsch"];
    readonly dv: readonly ["Divehi", "ދިވެހިބަސް"];
    readonly dz: readonly ["Dzongkha", "ཇོང་ཁ"];
    readonly ee: readonly ["Ewe", "Ɛʋɛ"];
    readonly el: readonly ["Greek", "Ελληνικά"];
    readonly en: readonly ["English", "English"];
    readonly eo: readonly ["Esperanto", "Esperanto"];
    readonly es: readonly ["Spanish", "Español"];
    readonly et: readonly ["Estonian", "Eesti"];
    readonly eu: readonly ["Basque", "Euskara"];
    readonly fa: readonly ["Persian", "فارسی"];
    readonly ff: readonly ["Peul", "Fulfulde"];
    readonly fi: readonly ["Finnish", "Suomi"];
    readonly fj: readonly ["Fijian", "Na Vosa Vakaviti"];
    readonly fo: readonly ["Faroese", "Føroyskt"];
    readonly fr: readonly ["French", "Français"];
    readonly fy: readonly ["West Frisian", "Frysk"];
    readonly ga: readonly ["Irish", "Gaeilge"];
    readonly gd: readonly ["Scottish Gaelic", "Gàidhlig"];
    readonly gl: readonly ["Galician", "Galego"];
    readonly gn: readonly ["Guarani", "Avañe'ẽ"];
    readonly gu: readonly ["Gujarati", "ગુજરાતી"];
    readonly gv: readonly ["Manx", "Gaelg"];
    readonly ha: readonly ["Hausa", "هَوُسَ"];
    readonly he: readonly ["Hebrew", "עברית"];
    readonly hi: readonly ["Hindi", "हिन्दी"];
    readonly ho: readonly ["Hiri Motu", "Hiri Motu"];
    readonly hr: readonly ["Croatian", "Hrvatski"];
    readonly ht: readonly ["Haitian", "Krèyol ayisyen"];
    readonly hu: readonly ["Hungarian", "Magyar"];
    readonly hy: readonly ["Armenian", "Հայերեն"];
    readonly hz: readonly ["Herero", "Otsiherero"];
    readonly ia: readonly ["Interlingua", "Interlingua"];
    readonly id: readonly ["Indonesian", "Bahasa Indonesia"];
    readonly ie: readonly ["Interlingue", "Interlingue"];
    readonly ig: readonly ["Igbo", "Igbo"];
    readonly ii: readonly ["Sichuan Yi", "ꆇꉙ / 四川彝语"];
    readonly ik: readonly ["Inupiak", "Iñupiak"];
    readonly io: readonly ["Ido", "Ido"];
    readonly is: readonly ["Icelandic", "Íslenska"];
    readonly it: readonly ["Italian", "Italiano"];
    readonly iu: readonly ["Inuktitut", "ᐃᓄᒃᑎᑐᑦ"];
    readonly ja: readonly ["Japanese", "日本語"];
    readonly jv: readonly ["Javanese", "Basa Jawa"];
    readonly ka: readonly ["Georgian", "ქართული"];
    readonly kg: readonly ["Kongo", "KiKongo"];
    readonly ki: readonly ["Kikuyu", "Gĩkũyũ"];
    readonly kj: readonly ["Kuanyama", "Kuanyama"];
    readonly kk: readonly ["Kazakh", "Қазақша"];
    readonly kl: readonly ["Greenlandic", "Kalaallisut"];
    readonly km: readonly ["Cambodian", "ភាសាខ្មែរ"];
    readonly kn: readonly ["Kannada", "ಕನ್ನಡ"];
    readonly ko: readonly ["Korean", "한국어"];
    readonly kr: readonly ["Kanuri", "Kanuri"];
    readonly ks: readonly ["Kashmiri", "कश्मीरी / كشميري"];
    readonly ku: readonly ["Kurdish", "Kurdî / كوردی"];
    readonly kv: readonly ["Komi", "Коми"];
    readonly kw: readonly ["Cornish", "Kernewek"];
    readonly ky: readonly ["Kirghiz", "Kırgızca / Кыргызча"];
    readonly la: readonly ["Latin", "Latina"];
    readonly lb: readonly ["Luxembourgish", "Lëtzebuergesch"];
    readonly lg: readonly ["Ganda", "Luganda"];
    readonly li: readonly ["Limburgian", "Limburgs"];
    readonly ln: readonly ["Lingala", "Lingála"];
    readonly lo: readonly ["Laotian", "ລາວ / Pha xa lao"];
    readonly lt: readonly ["Lithuanian", "Lietuvių"];
    readonly lv: readonly ["Latvian", "Latviešu"];
    readonly mg: readonly ["Malagasy", "Malagasy"];
    readonly mh: readonly ["Marshallese", "Kajin Majel / Ebon"];
    readonly mi: readonly ["Maori", "Māori"];
    readonly mk: readonly ["Macedonian", "Македонски"];
    readonly ml: readonly ["Malayalam", "മലയാളം"];
    readonly mn: readonly ["Mongolian", "Монгол"];
    readonly mo: readonly ["Moldovan", "Moldovenească"];
    readonly mr: readonly ["Marathi", "मराठी"];
    readonly ms: readonly ["Malay", "Bahasa Melayu"];
    readonly mt: readonly ["Maltese", "bil-Malti"];
    readonly my: readonly ["Burmese", "Myanmasa"];
    readonly na: readonly ["Nauruan", "Dorerin Naoero"];
    readonly nd: readonly ["North Ndebele", "Sindebele"];
    readonly ne: readonly ["Nepali", "नेपाली"];
    readonly ng: readonly ["Ndonga", "Oshiwambo"];
    readonly nl: readonly ["Dutch", "Nederlands"];
    readonly nn: readonly ["Norwegian Nynorsk", "Norsk (nynorsk)"];
    readonly no: readonly ["Norwegian", "Norsk (bokmål / riksmål)"];
    readonly nr: readonly ["South Ndebele", "isiNdebele"];
    readonly nv: readonly ["Navajo", "Diné bizaad"];
    readonly ny: readonly ["Chichewa", "Chi-Chewa"];
    readonly oc: readonly ["Occitan", "Occitan"];
    readonly oj: readonly ["Ojibwa", "ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin"];
    readonly om: readonly ["Oromo", "Oromoo"];
    readonly or: readonly ["Oriya", "ଓଡ଼ିଆ"];
    readonly os: readonly ["Ossetian / Ossetic", "Иронау"];
    readonly pa: readonly ["Panjabi / Punjabi", "ਪੰਜਾਬੀ / पंजाबी / پنجابي"];
    readonly pi: readonly ["Pali", "Pāli / पाऴि"];
    readonly pl: readonly ["Polish", "Polski"];
    readonly ps: readonly ["Pashto", "پښتو"];
    readonly pt: readonly ["Portuguese", "Português"];
    readonly qu: readonly ["Quechua", "Runa Simi"];
    readonly rm: readonly ["Raeto Romance", "Rumantsch"];
    readonly rn: readonly ["Kirundi", "Kirundi"];
    readonly ro: readonly ["Romanian", "Română"];
    readonly ru: readonly ["Russian", "Русский"];
    readonly rw: readonly ["Rwandi", "Kinyarwandi"];
    readonly sa: readonly ["Sanskrit", "संस्कृतम्"];
    readonly sc: readonly ["Sardinian", "Sardu"];
    readonly sd: readonly ["Sindhi", "सिनधि"];
    readonly se: readonly ["Northern Sami", "Sámegiella"];
    readonly sg: readonly ["Sango", "Sängö"];
    readonly sh: readonly ["Serbo-Croatian", "Srpskohrvatski / Српскохрватски"];
    readonly si: readonly ["Sinhalese", "සිංහල"];
    readonly sk: readonly ["Slovak", "Slovenčina"];
    readonly sl: readonly ["Slovenian", "Slovenščina"];
    readonly sm: readonly ["Samoan", "Gagana Samoa"];
    readonly sn: readonly ["Shona", "chiShona"];
    readonly so: readonly ["Somalia", "Soomaaliga"];
    readonly sq: readonly ["Albanian", "Shqip"];
    readonly sr: readonly ["Serbian", "Српски"];
    readonly ss: readonly ["Swati", "SiSwati"];
    readonly st: readonly ["Southern Sotho", "Sesotho"];
    readonly su: readonly ["Sundanese", "Basa Sunda"];
    readonly sv: readonly ["Swedish", "Svenska"];
    readonly sw: readonly ["Swahili", "Kiswahili"];
    readonly ta: readonly ["Tamil", "தமிழ்"];
    readonly te: readonly ["Telugu", "తెలుగు"];
    readonly tg: readonly ["Tajik", "Тоҷикӣ"];
    readonly th: readonly ["Thai", "ไทย / Phasa Thai"];
    readonly ti: readonly ["Tigrinya", "ትግርኛ"];
    readonly tk: readonly ["Turkmen", "Туркмен / تركمن"];
    readonly tl: readonly ["Tagalog / Filipino", "Tagalog"];
    readonly tn: readonly ["Tswana", "Setswana"];
    readonly to: readonly ["Tonga", "Lea Faka-Tonga"];
    readonly tr: readonly ["Turkish", "Türkçe"];
    readonly ts: readonly ["Tsonga", "Xitsonga"];
    readonly tt: readonly ["Tatar", "Tatarça"];
    readonly tw: readonly ["Twi", "Twi"];
    readonly ty: readonly ["Tahitian", "Reo Mā`ohi"];
    readonly ug: readonly ["Uyghur", "Uyƣurqə / ئۇيغۇرچە"];
    readonly uk: readonly ["Ukrainian", "Українська"];
    readonly ur: readonly ["Urdu", "اردو"];
    readonly uz: readonly ["Uzbek", "Ўзбек"];
    readonly ve: readonly ["Venda", "Tshivenḓa"];
    readonly vi: readonly ["Vietnamese", "Tiếng Việt"];
    readonly vo: readonly ["Volapük", "Volapük"];
    readonly wa: readonly ["Walloon", "Walon"];
    readonly wo: readonly ["Wolof", "Wollof"];
    readonly xh: readonly ["Xhosa", "isiXhosa"];
    readonly yi: readonly ["Yiddish", "ייִדיש"];
    readonly yo: readonly ["Yoruba", "Yorùbá"];
    readonly za: readonly ["Zhuang", "Cuengh / Tôô / 壮语"];
    readonly zh: readonly ["Chinese", "中文"];
    readonly zu: readonly ["Zulu", "isiZulu"];
};
export type Country = keyof typeof currencyCodeMap;
export type Currency = typeof currencyCodeMap[Country];
export type Language = keyof typeof languageMap;
export type Locale = `${Language}-${Country}`;
export declare const isCountry: (str?: string) => str is Country;
export declare const isLanguage: (str?: string) => str is Language;
export declare const isLocale: (str?: string) => str is Locale;
export declare const splitLocale: (locale?: Locale | Language | Country) => [Language | undefined, Country | undefined];
export declare const getLanguage: (locale: Locale | Language) => Language;
export declare const getCountry: (locale: Locale) => Country | undefined;
export declare const getCurrency: (locale: Locale | Country) => Currency;
export declare function formatCurrency(lt: Country | Locale, currency: Currency, value: number): string;
export declare function formatCurrency(lt: Country | Locale, currency: Currency): (_: number | bigint) => string;
export declare function formatNumber(lt: Country | Locale, separator: boolean, value: number): string;
export declare function formatNumber(lt: Country | Locale, separator: boolean): (_: number) => string;
export declare function formatDate(lt: Country | Locale, value: string): string;
export declare function formatDate(lt: Country | Locale): (_: string) => string;
export declare function formatDateTime(lt: Country | Locale, ISODate: string): string;
export declare function formatDateTime(lt: Country | Locale): (_: string) => string;
export declare const DEFAULT_CURRENCY: Currency;
export declare const DEFAULT_LANG: Language;
export declare const DEFAULT_LOCALE: Locale;
export {};
//# sourceMappingURL=grud-intl.d.ts.map