"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isStatusColumn = exports.isDateTimeColumn = exports.isDateColumn = exports.isTextColumn = exports.isShorttextColumn = exports.isRichtextColumn = exports.isNumberColumn = exports.isLinkColumn = exports.isIntegerColumn = exports.isGroupColumn = exports.isConcatColumn = exports.isCurrencyColumn = exports.isBooleanColumn = exports.isAttachmentColumn = exports.isMultilangColumn = void 0;
const index_js_1 = require("./types/index.js");
const isMultilangColumn = (column) => column.multilanguage;
exports.isMultilangColumn = isMultilangColumn;
const isAttachmentColumn = (column) => column.kind === index_js_1.ColumnKind.attachment;
exports.isAttachmentColumn = isAttachmentColumn;
const isBooleanColumn = (column) => column.kind === index_js_1.ColumnKind.boolean;
exports.isBooleanColumn = isBooleanColumn;
const isCurrencyColumn = (column) => column.kind === index_js_1.ColumnKind.currency;
exports.isCurrencyColumn = isCurrencyColumn;
const isConcatColumn = (column) => column.kind === index_js_1.ColumnKind.concat;
exports.isConcatColumn = isConcatColumn;
const isGroupColumn = (column) => column.kind === index_js_1.ColumnKind.group;
exports.isGroupColumn = isGroupColumn;
const isIntegerColumn = (column) => column.kind === index_js_1.ColumnKind.integer;
exports.isIntegerColumn = isIntegerColumn;
const isLinkColumn = (column) => column.kind === index_js_1.ColumnKind.link;
exports.isLinkColumn = isLinkColumn;
const isNumberColumn = (column) => column.kind === index_js_1.ColumnKind.numeric;
exports.isNumberColumn = isNumberColumn;
const isRichtextColumn = (column) => column.kind === index_js_1.ColumnKind.richtext;
exports.isRichtextColumn = isRichtextColumn;
const isShorttextColumn = (column) => column.kind === index_js_1.ColumnKind.shorttext;
exports.isShorttextColumn = isShorttextColumn;
const isTextColumn = (column) => column.kind === index_js_1.ColumnKind.text;
exports.isTextColumn = isTextColumn;
const isDateColumn = (column) => column.kind === index_js_1.ColumnKind.date;
exports.isDateColumn = isDateColumn;
const isDateTimeColumn = (column) => column.kind === index_js_1.ColumnKind.datetime;
exports.isDateTimeColumn = isDateTimeColumn;
const isStatusColumn = (column) => column.kind === index_js_1.ColumnKind.status;
exports.isStatusColumn = isStatusColumn;
