name: Deno CI

on:
  push:
    branches: [jsr]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
      
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.1.7
      
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Check types
        run: deno check mod.ts

      - name: Run tests
        run: deno task test

      - name: Publish to JSR
        run: deno publish
