name: Test
on: [pull_request, push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v14
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: build packages
        run: nix build '.#default'
      - name: run tests
        run: nix run '.#checks'
